CREATE MASTER KEY ENCRYPTION BY  
PASSWORD = 'CTC@Encrypt2020'

CREATE CERTIFICATE APPSelfSignedCertificate  
WITH SUBJECT = 'APP Encryption';  
GO  

SELECT * FROM sys.certificates

CREATE SYMMETRIC KEY APPSymmetricKey  
WITH ALGORITHM = AES_128  
ENCRYPTION BY CERTIFICATE APPSelfSignedCertificate;  
GO 
